# Generated by Django 4.1.6 on 2023-02-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_film_description_alter_film_rating_authoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoring',
            name='password',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='authoring',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
